### ISSUE TITLE
[Raspberry PI 3][MySQL 5.7] Beginner Help ! 

### ISSUE THREAD

**Issue by Ran-snow** [biarms/mysql#1]
Hi,we use "docker pull biarms/mysql:5.7",but  it can't run
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

pi@raspberrypi:~ $ docker run --name mysql01 -e MYSQL_ROOT_PASSWORD=xxx -p 3306:3306 --rm biarms/mysql:5.7
Initializing database
180501 14:07:45 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
180501 14:07:45 [Note] mysqld (mysqld 5.5.59-0ubuntu0.14.04.1) starting as process 35 ...
180501 14:07:45 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
180501 14:07:45 [Note] Plugin 'FEDERATED' is disabled.
mysqld: Table 'mysql.plugin' doesn't exist
180501 14:07:45 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
180501 14:07:45 InnoDB: The InnoDB memory heap is disabled
180501 14:07:45 InnoDB: Mutexes and rw_locks use GCC atomic builtins
180501 14:07:45 InnoDB: Compressed tables use zlib 1.2.8
180501 14:07:45 InnoDB: Using Linux native AIO
180501 14:07:45 InnoDB: Initializing buffer pool, size = 128.0M
180501 14:07:45 InnoDB: Completed initialization of buffer pool
InnoDB: The first specified data file ./ibdata1 did not exist:
InnoDB: a new database to be created!
180501 14:07:45  InnoDB: Setting file ./ibdata1 size to 10 MB
InnoDB: Database physically writes the file full: wait...
180501 14:07:46  InnoDB: Log file ./ib_logfile0 did not exist: new to be created
InnoDB: Setting log file ./ib_logfile0 size to 5 MB
InnoDB: Database physically writes the file full: wait...
180501 14:07:47  InnoDB: Log file ./ib_logfile1 did not exist: new to be created
InnoDB: Setting log file ./ib_logfile1 size to 5 MB
InnoDB: Database physically writes the file full: wait...
InnoDB: Doublewrite buffer not found: creating new
InnoDB: Doublewrite buffer created
InnoDB: 127 rollback segment(s) active.
InnoDB: Creating foreign key constraint system tables
InnoDB: Foreign key constraint system tables created
180501 14:07:53  InnoDB: Waiting for the background threads to start
180501 14:07:54 InnoDB: 5.5.59 started; log sequence number 0
180501 14:07:54 [ERROR] mysqld: unknown option '--initialize-insecure'
180501 14:07:54 [ERROR] Aborting

180501 14:07:54  InnoDB: Starting shutdown...
180501 14:07:57  InnoDB: Shutdown completed; log sequence number 1595675
180501 14:07:57 [Note] mysqld: Shutdown complete

**Comment by biarms** [comment]
I should have fixed your issue. Try: 
'docker pull biarms/mysql'
Then
'docker run --name mysql01 -e MYSQL_ROOT_PASSWORD=xxx -p 3306:3306 --rm biarms/mysql'

**Comment by Ran-snow** [comment]
Thank you !
