### ISSUE TITLE
Disabling ONLY_FULL_GROUP_BY

### ISSUE THREAD

**Issue by korgoth** [biarms/mysql#6]
Hello, 

i am using those images on an ARM based Macbook Pro and i am unable to understand how to permanently disable the ONLY_FULL_GROUP_BY option in sql_mode. 

If i start the container and run a SQL to disable this option its working fine, but i can't seem to be able to disable it from the config files - tried all that i could find. 

What would be the best way to address this?

**Comment by kremerol** [comment]
Hello korgoth, 

I don't know all the mysql option, but I guess it is possible to disable it via editing the my.conf file.
Therefore, I suggest you to have a look on how to change this my.conf file in a docker env, as explained in the "Using a custom MySQL configuration file" section of the https://registry.hub.docker.com/_/mysql/ page. I hope it will help.

Best regards,
Olivier Kremer
